interface QuestionCategory {
  category: string;
  questions: string[];
}

export const SAMPLE_QUESTIONS: QuestionCategory[] = [
  {
    category: "Descriptive / Summary Statistics",
    questions: [
      "What is the total number of transactions in the dataset?",
      "What is the average transaction amount across all transactions?",
      "What is the median transaction amount?",
      "What are the minimum and maximum transaction amounts?",
      "What is the distribution of transactions across different device types?",
      "What is the breakdown of transaction statuses in the dataset?",
      "What is the overall transaction success rate?",
      "What is the total transaction volume in INR?",
      "How many transactions were flagged for fraud?",
      "What percentage of all transactions are flagged for fraud?",
      "What is the average transaction amount for bill payments?",
      "How many distinct merchant categories exist?",
      "What is the most common transaction type?",
      "What is the most common sender bank and receiver bank pair?",
      "What is the standard deviation of transaction amounts?",
    ],
  },
  {
    category: "Comparative Analysis",
    questions: [
      "How do failure rates compare between Android and iOS users?",
      "Compare the average transaction amount across all transaction types.",
      "Which sender bank has the highest success rate?",
      "How does the average transaction amount differ between sender age groups?",
      "Compare fraud flag rates across different device types.",
      "Which sender bank has the highest average transaction amount?",
      "Compare transaction volumes between P2P and merchant payments.",
      "How do success rates compare across different network types (WiFi, 4G, 5G)?",
      "Which receiver bank processes the most transactions?",
      "Compare the average transaction amount between weekday and weekend transactions.",
      "How do transaction amounts compare across different network types?",
      "Which transaction type has the highest failure rate?",
      "Compare the top 5 sender banks by total transaction volume.",
      "How does the fraud flag rate differ between high-value and low-value transactions?",
      "Which merchant category has the highest average transaction amount?",
    ],
  },
  {
    category: "Temporal / Time-Series Analysis",
    questions: [
      "What are the peak transaction hours across all transaction types?",
      "How does transaction volume vary by hour of day?",
      "What are the peak transaction hours for food delivery?",
      "How does the failure rate change across different hours of the day?",
      "What is the transaction volume trend by day of the week?",
      "How does transaction volume differ between weekdays and weekends?",
      "Are there more fraud-flagged transactions during late-night hours?",
      "What hour has the highest average transaction amount?",
      "How does the success rate vary by hour of day?",
      "What is the busiest day of the week for P2P transfers?",
      "During which hours do bill payments peak?",
      "How does weekend vs weekday transaction volume compare for each transaction type?",
      "What time of day has the highest fraud flag rate?",
      "Is there a pattern in transaction failures by day of week?",
      "What is the hourly distribution of high-value transactions (above 10,000 INR)?",
    ],
  },
  {
    category: "Segmentation / Group Analysis",
    questions: [
      "Which age group uses P2P transfers most frequently?",
      "What is the transaction volume breakdown by sender state for the top 10 states?",
      "Which sender state has the highest total transaction amount?",
      "What is the distribution of transactions across different sender banks?",
      "How are transactions distributed across merchant categories?",
      "Which age group has the highest average transaction amount?",
      "What is the transaction distribution by network type?",
      "Which sender bank handles the most P2P transfers?",
      "How do transaction types break down for the 18-25 age group?",
      "What is the device type distribution for each sender age group?",
      "Which receiver bank receives the most high-value transactions (above 10,000 INR)?",
      "What are the top 5 sender bank-receiver bank pairs by transaction count?",
      "How do transactions distribute across different days of the week?",
      "What percentage of transactions come from each network type?",
      "Which merchant category is most popular among the 26-35 age group?",
    ],
  },
  {
    category: "Correlation / Relationship Analysis",
    questions: [
      "Is there a relationship between network type and transaction success?",
      "Do high-value transactions fail more often than low-value ones?",
      "Is there a correlation between sender age group and fraud flags?",
      "Does the sender bank affect transaction success rates?",
      "Is there a relationship between device type and average transaction amount?",
      "Do transactions from certain states have higher failure rates?",
      "Is there a correlation between hour of day and transaction amount?",
      "Does network type affect the average transaction amount?",
      "Is there a relationship between merchant category and fraud flags?",
      "Do weekend transactions have different success rates than weekday ones?",
      "Is there a relationship between sender bank and transaction success rate?",
      "Does the receiver bank affect failure rates?",
      "Is there a correlation between transaction type and fraud flag rate?",
      "Do transactions from certain age groups have higher average amounts?",
      "Is there a pattern between day of week and transaction failures?",
    ],
  },
  {
    category: "Risk / Fraud Analysis",
    questions: [
      "What percentage of high-value transactions are flagged for review?",
      "Which sender banks show the highest fraud flag rates?",
      "Which merchant categories have the most fraud-flagged transactions?",
      "What is the average amount of fraud-flagged vs non-flagged transactions?",
      "Which age group has the highest fraud flag rate?",
      "Are fraud flags more common on certain device types?",
      "Which states have the highest fraud flag rates?",
      "What is the fraud flag rate for transactions above 50,000 INR?",
      "Is the fraud flag rate higher for transactions on certain days of the week?",
      "What is the fraud flag distribution by transaction type?",
      "Which hour of day has the most fraud-flagged transactions?",
      "Are weekend transactions more likely to be flagged for fraud?",
      "What is the fraud rate for each network type?",
      "Which sender-receiver bank combination has the highest fraud rate?",
      "What percentage of failed transactions are also fraud-flagged?",
    ],
  },
  {
    category: "Multi-Dimensional / Pivot Analysis",
    questions: [
      "Break down success rates by transaction type and device type.",
      "What is the average amount by age group and transaction type?",
      "Show fraud flag rates by merchant category and device type.",
      "Compare transaction volumes by sender state and transaction type for the top 5 states.",
      "What is the success rate by sender bank and network type for the top 5 banks?",
      "Break down average transaction amount by hour of day and transaction type.",
      "Show the fraud flag rate by age group and device type.",
      "Compare failure rates by sender bank and device type for the top 3 banks.",
      "What is the transaction count by merchant category and age group?",
      "Show the average amount by network type and time of day (morning/afternoon/evening/night).",
    ],
  },
  {
    category: "Edge Cases / Boundary Questions",
    questions: [
      "What is the highest single transaction amount in the dataset?",
      "Are there any transactions with zero amount?",
      "What is the smallest non-zero transaction amount?",
      "Are there any sender banks with a 100% success rate?",
      "Which merchant category has the single highest-value transaction?",
      "Are there any day of week and hour combinations with zero transactions?",
      "What percentage of transactions have the same sender and receiver bank?",
      "Are there any transactions at exactly midnight (hour 0)?",
      "What is the most common transaction amount (rounded to nearest 100 INR)?",
      "How many transactions fall in the amount range of exactly 1 INR?",
      "Are there sender banks that only appear on weekdays?",
      "What is the count of transactions with the maximum amount?",
      "How many distinct sender bank-receiver bank combinations exist?",
      "What is the most common sender bank and receiver bank combination?",
      "Are there merchant categories with zero fraud flags?",
    ],
  },
  {
    category: "Complex / Advanced Queries",
    questions: [
      "Which sender banks and device types show a disproportionately high fraud-flag rate during late-night hours on weekends?",
      "What is the 90th percentile transaction amount for each transaction type?",
      "Rank sender states by their fraud-to-transaction ratio, showing only states with more than 1000 transactions.",
      "What is the cumulative transaction volume by hour of day?",
      "Which age group and merchant category combination has the highest average transaction amount?",
      "Find the top 3 merchant categories by fraud flag rate for each sender age group.",
      "What is the running average of transaction amounts by hour?",
      "Which network types show the biggest difference in success rates between peak hours (9-17) and off-peak hours?",
      "Which sender banks have an average transaction amount more than 2 times the overall average?",
      "What percentage of each transaction type's volume comes from the top 5 sender states?",
    ],
  },
  {
    category: "Intentional Traps / Ambiguous Questions",
    questions: [
      "What is the total revenue?",
      "Show me the profit margin by category.",
      "What is the customer lifetime value?",
      "How many returns were processed?",
      "What is the churn rate?",
      "Show me the inventory levels.",
      "What is the conversion rate?",
      "How many products were sold?",
      "What is the average delivery time?",
      "Show me the customer satisfaction scores.",
      "What is the net promoter score?",
      "How many active subscriptions are there?",
      "What is the bounce rate?",
      "Show me the marketing campaign performance.",
      "What is the employee count by department?",
    ],
  },
  {
    category: "Stress Test / Large Result Set Questions",
    questions: [
      "List all unique sender bank and receiver bank combinations with their transaction counts and success rates.",
      "Show the complete hourly breakdown of every transaction type and merchant category combination.",
      "What is the transaction count for every unique combination of sender state, merchant category, and transaction type?",
      "Show every sender bank that has transactions in all merchant categories.",
      "Show the hourly transaction pattern for each merchant category across all hours of the day.",
      "What is the success rate for every combination of sender bank, receiver bank, and device type?",
      "Generate a cross-tab of fraud flag rates by sender state and age group for all states.",
    ],
  },
];
